schock:
  pca_data_path: "/home/schock/Downloads/preds"
  network_train_path: "/home/schock/Downloads/preds"
  validation_path: "/home/schock/Downloads/preds"
  network_type: "ShapeNet"
  output_path: "/home/schock/Downloads/Shape_Test/Outputs"
  verbose: True
  img_size: 224
  initial_lr: 1e-4
  num_epochs: 50
  num_shape_params: 25
  num_global_params: 1
  num_translation_params: 2
  scale: True
  center: True
  norm: "instance"
  batch_size: 1
  use_cpp: True
